name: Build And test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  print-runtime-context:
    runs-on: ubuntu-latest
    steps:

      - &echo-template
          name: Echo template
          run: echo "This is a reusable step."
          shell: bash
        
      - name: print context push
        if: github.event_name == 'push'
        run: |
          echo "Workflow: ${{github.workflow}}"
          echo "Repo: ${{github.action_repository}}"
          echo "Trigger event: ${{github.event_name}}"
          echo "Triggered by: ${{github.triggering_actor}}"
          echo "Branch: ${{github.ref}}"
          echo "Runner: ${{runner.os}}"
          echo "Commit Message: ${{github.event.head_commit.message}}"

      - name: print context pr
        if: github.event_name == 'pull_request'
        run: |
          echo "Workflow: ${{github.workflow}}"
          echo "Repo: ${{github.action_repository}}"
          echo "Trigger event: ${{github.event_name}}"
          echo "Triggered by: ${{github.triggering_actor}}"
          echo "Branch: ${{github.ref}}"
          echo "Runner: ${{runner.os}}"
          echo "Target Branch: ${{github.base_ref}}"
          
      - name: print context workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Workflow: ${{github.workflow}}"
          echo "Repo: ${{github.action_repository}}"
          echo "Trigger event: ${{github.event_name}}"
          echo "Triggered by: ${{github.triggering_actor}}"
          echo "Branch: ${{github.ref}}"
          echo "Runner: ${{runner.os}}" 
          echo "Runner: ${{inputs}}" 
        
      - *echo-template
      
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{matrix.version}}

      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore

      - name: Test with the dotnet CLI
        run: dotnet test --no-build --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
        
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.version }}-${{ matrix.os }}
          path: TestResults-${{ matrix.version }}

        

      
